server:
 port: 9000

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/SpringAuthServer
  username: postgres
  password: P@ssw0rd
 jpa:  
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:   
   dialect: org.hibernate.dialect.PostgreSQLDialect